[tool.poetry]
name = "pstable"
version = "0.1.0"
description = ""
authors = ["RJ Rybarczyk <rj@rybar.tech>"]

[tool.poetry.dependencies]
python = "^3.9"
cffi = "^1.14.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
